name: Docker Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on new SemVer tags
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: "${{ steps.tags.outputs.tags }}"
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-meta@v2
        name: generate tags
        id: tags
        with:
          images: ghcr.io/siafoundation/siad
          tags: |
            type=semver,pattern={{version}}

  docker:
    runs-on: ubuntu-latest
    needs: get-tags
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ needs.get-tags.outputs.tags }}
